version: '3.3'
services:
  db:
    build:
      context: ./database
    restart: always
    environment:
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'zeroaxlx'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'zeroaxlx'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
  app:
    build:
      context: .
    depends_on: 
      - db
    ports:
      - "3000:3000"
    volumes:
    - ./:/usr/src/nodejs-quiz-app/
